version: "3.8"
networks:
  my-bridge:
    external:
      name: my-bridge
services:
  online-chat-backend:
    build: .
    image: ixuewen/online-chat-backend
    container_name: online-chat-backend-docker
    restart: always
    networks:
      - my-bridge
    ports:
      - 8002:8002
    volumes:
      - /var/docker-volume/online-chat-backend/upload-files:/root/upload-files
