spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    username: chat
    password: chat-2019
    url: jdbc:mysql://47.101.53.141:3306/chat?useUnicode=true&characterEncoding=utf8

  redis:
    host: 47.101.53.141
    port: 6379
    password:
    timeout: 2000ms

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

server:
  port: 8002
logging:
  level:
    root: INFO
